src/models/model_music.py
import enum

from config.database import db
from sqlalchemy import Enum

class GenreEnum(enum.Enum):
    Pop = "Pop"
    Rock = "Rock"
    Jazz = "Jazz"
    Funk = "Funk"
    Eletronica = "Eletronica"

class Music(db.Model):

    __tablename__ = 'musics'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    name = db.Column(db.String(120), nullable=False)
    artist = db.Column(db.String(120), nullable=False)
    genre = db.Column(Enum(GenreEnum), nullable=False)
    cover = db.Column(db.LargeBinary, nullable=True) 

    def __repr__(self):
        return f'<Music {self.name} by {self.artist}>'

src/models/model_user.py
from config.database import db

class User(db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(120), nullable=False)

    def __repr__(self):
        return f'<User {self.username}>'

src/app.py
from config.database import create_app, db

app = create_app()

with app.app_context():
    db.create_all() 
    try:
        connection = db.engine.connect()
        print("[DEBUG] Conectado BD com sucesso!")
        connection.close()

    except Exception as e:
        print(f"[DEBUG] Erro ao conectar ao BD: {e}")

if __name__ == '__main__':
    app.run(debug=True)

src/controllers/controller_music.py
from config.database import db
from flask import render_template, request, redirect, url_for, flash, session

from models.model_music import Music, GenreEnum
from models.model_user import User

def list_music():
    if not session.get('username'):
        return redirect(url_for('main.authenticar'))
    
    user = User.query.filter_by(username=session.get('username')).first()
    musics = Music.query.order_by(Music.id).filter(user.id == Music.user_id).all()
    return render_template('views/list_music.html', list_music=musics)

def add_music():
    if not session.get('username'):
        return redirect(url_for('main.authenticar'))
    
    if request.method == 'POST':
        name = request.form.get('name')
        artist = request.form.get('artist')
        genre = request.form.get('genre')

        user = User.query.filter_by(username=session.get('username')).first()
        music = Music.query.filter_by(name=name, user_id=user.id).first()

        if music:
            flash('Music already registered!', 'error')
            return redirect(url_for('main.add_music'))
        else:
            music = Music(user_id=user.id, name=name, artist=artist, genre=genre)
            db.session.add(music)
            db.session.commit()
            flash('Music added successfully!', 'success')
            return redirect(url_for('main.list_music'))
        
    else:
        return render_template('views/add_music.html', genres=GenreEnum)
    
def edit_music(music_id):
    if not session.get('username'):
        return redirect(url_for('main.authenticar'))
    
    music = Music.query.get(music_id)

    if request.method == 'POST':
        music.name = request.form['name']
        music.artist = request.form['artist']
        music.genre = request.form['genre']

        db.session.commit()
        flash('Music updated successfully!', 'success')
        return redirect(url_for('main.list_music'))
    
    else:
        return render_template('views/edit_music.html', music=music, genres=GenreEnum)
    
def del_music(music_id):
    if not session.get('username'):
        return redirect(url_for('main.authenticar'))
    
    music = Music.query.get(music_id)
    db.session.delete(music)
    db.session.commit()
    flash('Music deleted successfully!', 'success')
    return redirect(url_for('main.list_music'))

src/controllers/controller_user.py
from config.database import db
from flask import render_template, request, redirect, url_for, flash, session

from models.model_user import User

def add_user():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
    
        user = User.query.filter_by(username=username).first()

        if user:
            flash('User already registered!', 'error')
            return redirect(url_for('main.add_user'))
        
        else:
            user = User(username=username, password=password)
            db.session.add(user)
            db.session.commit()
            flash('User added successfully!', 'success')
            return redirect(url_for('main.list_music'))
    else:
        return render_template('views/add_user.html')
    
def authenticar():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username, password=password).first()

        if user:
            session['username'] = request.form['username']
            flash(f'Login {user.username} successful!', 'success')
            return redirect(url_for('main.list_music'))
        else:
            flash('Invalid username or password!', 'error')
            return redirect(url_for('main.authenticar'))
    else:
        return render_template('views/login.html')

def logout():
    session.pop('username', None)
    flash('Logged out successfully!', 'success')
    return redirect(url_for('main.authenticar'))

src/routes/routes.py
import os

from flask import Blueprint
from controllers.controller_music import list_music, add_music, edit_music, del_music
from controllers.controller_user import add_user, authenticar, logout

TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'templates')

main = Blueprint('main', __name__, template_folder=TEMPLATE_DIR)

main.add_url_rule('/', 'list_music', list_music)
main.add_url_rule('/add_music', 'add_music', add_music, methods=['GET','POST'])
main.add_url_rule('/add_user', 'add_user', add_user, methods=['GET','POST'])
main.add_url_rule('/authenticar', 'authenticar', authenticar, methods=['GET','POST'])
main.add_url_rule('/logout', 'logout', logout)
main.add_url_rule('/edit_music/<int:music_id>', 'edit_music', edit_music, methods=['GET','POST'])
main.add_url_rule('/del_music/<int:music_id>', 'del_music', del_music)

src/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block head %}{% endblock %}

</head>
<body>

    <header>
        <nav>
            <ul>
                {% if not session.get('username') %}
                    <li><a href="{{ url_for('main.add_user') }}">User</a></li>
                    <li><a href="{{ url_for('main.authenticar') }}">Login</a></li>
                {% endif %}
                {% if session.get('username') %}
                    <li><a href="{{ url_for('main.add_music')}}">Add</a></li>
                    <li><a href="{{ url_for('main.list_music')}}">List</a></li>
                    <li><a href="{{ url_for('main.logout') }}">Sair</a></li>
                    <li>{{ session['username'] }}</li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        <div>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
        </div>
        <div>
            {% block body %}{% endblock %}
        </div>
    </main>
    
</body>
</html>

src/templates/views/add_music.html
{% extends 'base.html' %}

{% block head %} <title>Music | Add</title> {% endblock %}

{% block body %}
    
    <div>
        <h1>Bem Vindo ao Music</h1>

    <form method="POST" action="/add_music">

        <div>
            <label for="name">Nome da Música:</label>
            <input type="text" id="name" name="name" required>
        </div>

        <div>
            <label for="artist">Artista:</label>
            <input type="text" id="artist" name="artist" required>
        </div>

        <div>
            <label for="genre">Gênero:</label>
            <select id="genre" name="genre" required>
                <option value="">-- Selecione --</option>
                {% for g in genres %}
                    <option value="{{ g.value }}">{{ g.value }}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <button type="submit">Adicionar Música</button>
        </div>
    </form>

    </div>

{% endblock %}

src/templates/views/add_user.html
{% extends 'base.html' %}

{% block head %} <title>Music | Add</title> {% endblock %}

{% block body %}
    
    <div>
        <h1>Bem Vindo ao Music</h1>

    <form method="POST" action="/add_user">

        <div>
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
        </div>

        <div>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
        </div>

        <div>
            <button type="submit">Adicionar User</button>
        </div>
    </form>

    </div>

{% endblock %}

src/templates/views/edit_music.html
{% extends 'base.html' %}

{% block head %} <title>Music | Add</title> {% endblock %}

{% block body %}
    
    <div>
        <h1>Bem Vindo ao Music</h1>

    <form method="POST" action="{{ url_for('main.edit_music', music_id=music.id) }}">

        <div>
            <label for="name">Nome da Música:</label>
            <input type="text" id="name" name="name" value="{{ music.name }}" required>
        </div>

        <div>
            <label for="artist">Artista:</label>
            <input type="text" id="artist" name="artist" value="{{ music.artist }}" required>
        </div>

        <div>
            <label for="genre">Gênero:</label>
            <select id="genre" name="genre" required>
                <option value="">-- Selecione --</option>
                {% for g in genres %}
                    <option value="{{ g.value }}" {% if g.value == music.genre.value %}selected{% endif %}>
                        {{ g.value }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <div>
            <button type="submit">Editar Música</button>
        </div>
    </form>

    </div>

{% endblock %}

src/templates/views/list_music.html
{% extends 'base.html' %}

{% block head %} <title>Music | List</title> {% endblock %}

{% block body %}
    
    <div>
        <h1>Bem Vindo ao Music</h1>

    <ul>
    {% for music in list_music %}
        <li>{{ music.user_id }} - {{ music.id }} - {{ music.name }} - {{ music.artist }} - {{ music.genre.value }} - 
            <a href="{{ url_for('main.edit_music', music_id=music.id)}}">Editar</a>
            <a href="{{ url_for('main.del_music', music_id=music.id )}}">Excluir</a>
        </li>
    {% else %}
        <li>Nenhuma música cadastrada.</li>
    {% endfor %}
    </ul>

    </div>

{% endblock %}

src/templates/views/login.html
{% extends 'base.html' %}

{% block head %} <title>Music | Login</title> {% endblock %}

{% block body %}
    
    <div>
        <h1>Bem Vindo ao Music</h1>

    <form method="POST" action="/authenticar">

        <div>
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
        </div>

        <div>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
        </div>

        <div>
            <button type="submit">Entrar</button>
        </div>
    </form>

    </div>

{% endblock %}